# Generated by Django 3.2.16 on 2022-10-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_productentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='product_image',
            field=models.ImageField(default='', upload_to='templates/roupas'),
        ),
    ]
