# Generated by Django 3.2.16 on 2022-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_customer_order_product_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='product_description',
            field=models.CharField(default='Description not found.', max_length=500),
        ),
    ]
