# Generated by Django 4.1.3 on 2022-11-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_auto_20221122_2000"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=60)),
                ("client_password", models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name="order_item",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="homepage.productentry",
            ),
        ),
        migrations.AlterField(
            model_name="productentry",
            name="product_price",
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
