# Generated by Django 4.1.3 on 2022-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_clienteentry_alter_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productentry",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
