# Generated by Django 4.1.3 on 2022-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_alter_productentry_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productentry",
            name="product_image",
            field=models.ImageField(default="", upload_to="templates/roupas"),
        ),
    ]
