# Generated by Django 4.2.1 on 2023-05-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20230528_1627"),
        ("homepage", "0009_alter_productentry_product_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClienteEntry",
        ),
        migrations.AlterField(
            model_name="order_item",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productentry",
            ),
        ),
        migrations.DeleteModel(
            name="ProductEntry",
        ),
    ]
