# Generated by Django 3.2.16 on 2023-06-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_delete_clienteentry_delete_product_entry_example_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="product_entry_example",
        ),
    ]
