# Generated by Django 4.2.1 on 2023-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(default="", upload_to="templates/roupas"),
                ),
                ("product_name", models.CharField(max_length=60)),
                (
                    "product_size",
                    models.CharField(
                        choices=[
                            ("PP", "PP"),
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                        ],
                        max_length=2,
                    ),
                ),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "product_description",
                    models.CharField(default="Description not found.", max_length=500),
                ),
            ],
        ),
    ]
