# Generated by Django 4.2.1 on 2023-05-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO products_productentry (
                    id,
                    product_image,
                    product_name,
                    product_size,
                    product_price,
                    product_description
                )
                SELECT
                    id,
                    product_image,
                    product_name,
                    product_size,
                    product_price,
                    product_description
                FROM
                    homepage_productentry;
            """, reverse_sql="""
                INSERT INTO homepage_productentry (
                    id,
                    product_image,
                    product_name,
                    product_size,
                    product_price,
                    product_description
                )
                SELECT
                    id,
                    product_image,
                    product_name,
                    product_size,
                    product_price,
                    product_description
                FROM
                    products_productentry;
            """)
    ]

