# Generated by Django 3.2.16 on 2023-06-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20230528_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productentry",
            name="product_description",
            field=models.CharField(
                default="Description not found.",
                max_length=500,
                verbose_name="Descrição do Produto",
            ),
        ),
        migrations.AlterField(
            model_name="productentry",
            name="product_image",
            field=models.ImageField(
                default="", upload_to="", verbose_name="Imagem (.png)"
            ),
        ),
        migrations.AlterField(
            model_name="productentry",
            name="product_name",
            field=models.CharField(max_length=60, verbose_name="Titulo do Produto"),
        ),
        migrations.AlterField(
            model_name="productentry",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=30, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="productentry",
            name="product_size",
            field=models.CharField(
                choices=[
                    ("PP", "PP"),
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                ],
                max_length=2,
                verbose_name="Tamanho",
            ),
        ),
    ]
